name: Update Scrobble

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch and Process Track Info
      run: |
        # Fetch the current scrobbling track info directly from Last.fm API
        track_info=$(curl -s "https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=${{ secrets.LASTFM_USERNAME }}&api_key=${{ secrets.LASTFM_API_KEY }}&format=json&limit=1" |
        jq -r '.recenttracks.track[0] | "Currently Scrobbling: \(.artist[\"#text\"]) - \(.name) (Album: \(.album[\"#text\"]))"')

        # Output the track info for debugging
        echo "Track info: $track_info"

        # Update the HTML file with track info
        sed -i 's|<p id="scrobble-info">.*</p>|<p id="scrobble-info">'"$track_info"' </p>|' index.html

    - name: Commit and Push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add index.html
        git commit -m "Update scrobble [skip ci]"
        git push

