name: Update Scrobble

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch and Process Track Info
      run: |
        set -e
        track_info=$(curl -s "https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=${{ secrets.LAST_FM_USERNAME }}&api_key=${{ secrets.LAST_FM_API_KEY }}&format=json&limit=1" |
        jq -r '
        .recenttracks.track[0] | 
        "Currently Scrobbling: \(.artist["#text"]) - \(.name) (Album: \(.album["#text"]))"
        ')

        # Debugging: Output the raw track_info
        echo "Raw track info: $track_info"

        # Escape special characters
        escaped_track_info=$(printf '%s' "$track_info" | sed 's/[&/\]/\\&/g')

        # Debugging: Output the escaped track_info
        echo "Escaped track info: $escaped_track_info"

        # Update the HTML file with track info
        echo "<p id=\"scrobble-info\">$escaped_track_info</p>" > temp.html
        mv temp.html index.html
    - name: Commit and Push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        # Check if there are any changes
        if git diff --quiet --exit-code; then
          echo "No changes, skipping commit"
        else
          git add index.html
          git commit -m "Update scrobble info: ${escaped_track_info}"
          git remote set-url origin https://github-actions:${github.token}@github.com/CrushedCookieNut/crushedcookienut.github.io.git
          git push origin master
        fi
